name: Context checking
on: pull_request

jobs:
  conn_execute:
    if:  github.event_name == 'pull_request' && contains(fromJson('["Conn.Execute"]'), github.event.action)
    steps:
      - name: Paramétrer les requêtes
        run: echo "Requêtes à  paramétrer."
